ARG N8N_VERSION=2.8.3
FROM n8nio/runners:${N8N_VERSION}
USER root

RUN cd /opt/runners/task-runner-javascript && \
    pnpm add moment uuid @binance/spot @binance/common trading-signals
COPY config/n8n-task-runners.json /etc/n8n-task-runners.json

USER runner
